name: Run Agent Every Hour

on:
  workflow_dispatch:       # allows manual trigger

env:
  EMAIL_SENDER: "vikiscripts@gmail.com"
  EMAIL_RECEIVER: "vikas110@gmail.com"
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  
jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python venv for agent
        run: bash setup-env.sh

      - name: Run agent
        run: bash run-agent.sh
